/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progresscheck;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Prerna
 */
public class question extends javax.swing.JFrame {

    /**
     * Creates new form question
     */
    public question() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        option_1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        option_2 = new javax.swing.JTextField();
        option_3 = new javax.swing.JTextField();
        answer = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        option_4 = new javax.swing.JTextField();
        next1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        topic = new javax.swing.JTextField();
        subject = new javax.swing.JComboBox<>();
        level = new javax.swing.JComboBox<>();
        question = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 103, 123));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("OPTION 2:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 60));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("SET QUESTIONS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 380, 60));

        option_1.setColumns(100);
        option_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        option_1.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(option_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 490, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setText("TOPIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 60));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 0));
        jLabel5.setText("OPTION 3:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, 60));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 0));
        jLabel6.setText("Answer:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, 60));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("OPTION 1:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, 60));

        option_2.setColumns(100);
        option_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        option_2.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(option_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 490, -1));

        option_3.setColumns(100);
        option_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        option_3.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(option_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 490, -1));

        answer.setColumns(100);
        answer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answer.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 490, -1));

        finish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finish.setForeground(new java.awt.Color(102, 102, 0));
        finish.setText("FINISH...");
        finish.setBorder(new javax.swing.border.MatteBorder(null));
        finish.setOpaque(false);
        finish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishMouseClicked(evt);
            }
        });
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 170, 40));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 0));
        jLabel8.setText("OPTION 4:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 60));

        option_4.setColumns(100);
        option_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        option_4.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(option_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 490, -1));

        next1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next1.setForeground(new java.awt.Color(102, 102, 0));
        next1.setText("NEXT...");
        next1.setBorder(new javax.swing.border.MatteBorder(null));
        next1.setOpaque(false);
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        jPanel1.add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 170, 40));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 0));
        jLabel9.setText("QUESTION:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 60));

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 0));
        jLabel10.setText("SUBJECT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 60));

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 0));
        jLabel11.setText("LEVEL");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 60));

        topic.setColumns(100);
        topic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topic.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 490, -1));

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operating Systems", "OOP concepts", " " }));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 490, -1));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic", "Intermediate", "Difficult", "Challenge" }));
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 490, -1));

        question.setColumns(100);
        question.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        question.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 490, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
         String topic1 = topic.getText();
         String sub_val=subject.getSelectedItem().toString();
         String level_val=level.getSelectedItem().toString();
         String question1=question.getText();
        String option1 = option_1.getText();
       String option2 = option_2.getText();
       String option3 = option_3.getText();
       String option4 = option_4.getText();
       String answer1 = answer.getText();
        
        if (question1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Question");
        } else if (option1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (option2.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (option3.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (option4.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (answer1.equals("")) {
            JOptionPane.showMessageDialog(null, "Please specify correct option");
        }
        
        else {

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/exams","root","");
                 String query="insert into `questions`(`question_name`,`option1`,`option2`,`option3`,`option4`,`answer`,`subject`,`level`,`topic`) values(?,?,?,?,?,?,?,?,?)";
                PreparedStatement insert=con.prepareStatement(query);
                insert.setString(1,question1);
                insert.setString(2,option1);
                insert.setString(3, option2);
               // ResultSet rs=insert.executeQuery();
               insert.setString(4,option3);
                 insert.setString(5,option4);
                insert.setString(6, answer1);
                insert.setString(7, sub_val);
                insert.setString(8, level_val);
                insert.setString(9, topic1);
                
                if ( insert.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "New Question Added");
                   this.setVisible(false);
                      new MCQ_questions().setVisible(true);
                  }
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
            }
           
        }
       
        
        
    }//GEN-LAST:event_finishActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        // TODO add your handling code here:
		String topic1 = topic.getText();
         String sub_val=subject.getSelectedItem().toString();
         String level_val=level.getSelectedItem().toString();
         String question1=question.getText();
        String option1 = option_1.getText();
       String option2 = option_2.getText();
       String option3 = option_3.getText();
       String option4 = option_4.getText();
       String answer1 = answer.getText();

        if (question1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Question");
        } else if (option1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (option2.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (option3.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (option4.equals("")) {
            JOptionPane.showMessageDialog(null, "Add an option");
        }
        else if (answer1.equals("")) {
            JOptionPane.showMessageDialog(null, "Please specify correct option");
        }
        
        else {

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/exams","root","");
                String query="insert into `questions`(`question_name`,`option1`,`option2`,`option3`,`option4`,`answer`,`subject`,`level`,`topic`) values(?,?,?,?,?,?,?,?,?)";
                PreparedStatement insert=con.prepareStatement(query);
               // insert.setString(1,topic.getText());
               // ResultSet rs=insert.executeQuery();
                  /* insert.setString(2,option1);
                insert.setString(3, option2);
                insert.setString(4, option3);
                insert.setString(5, option4);
                insert.setString(6, answer1);*/
                   insert.setString(1,question1);
                insert.setString(2,option1);
                insert.setString(3, option2);
               // ResultSet rs=insert.executeQuery();
               insert.setString(4,option3);
                 insert.setString(5,option4);
                insert.setString(6, answer1);
                insert.setString(7, sub_val);
                insert.setString(8, level_val);
                insert.setString(9, topic1);
                
                  
                if ( insert.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "New Question Added");
                    topic.setText("");
                    question.setText("");
                    option_1.setText("");
                     option_2.setText("");
                      option_3.setText("");
                       option_4.setText("");
                       answer.setText("");
                }
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
            }
           
        }
    }//GEN-LAST:event_next1ActionPerformed

    private void finishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_finishMouseClicked

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JButton next1;
    private javax.swing.JTextField option_1;
    private javax.swing.JTextField option_2;
    private javax.swing.JTextField option_3;
    private javax.swing.JTextField option_4;
    private javax.swing.JTextField question;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JTextField topic;
    // End of variables declaration//GEN-END:variables
}
